[[LibFramehopUnwind]]
arch = "aarch64"
git-tree-sha1 = "4b370d6c9f1cd85c5e29293916d726a40ffd9f08"
os = "macos"

    [[LibFramehopUnwind.download]]
    sha256 = "1a8eedf5993cd83cd029fa78335d8a6591abcd749e06334e1b2e47f0491dd8f6"
    url = "https://github.com/JuliaBinaryWrappers/LibFramehopUnwind_jll.jl/releases/download/LibFramehopUnwind-v0.1.0+0/LibFramehopUnwind.v0.1.0.aarch64-apple-darwin.tar.gz"
[[LibFramehopUnwind]]
arch = "aarch64"
git-tree-sha1 = "d19e1ce982a49d4afe73ddff47506ddc771a7b1f"
libc = "glibc"
os = "linux"

    [[LibFramehopUnwind.download]]
    sha256 = "d494f86e418820e30eddc2d18f6c39ff607ada101d2ef758b69132c31b94af30"
    url = "https://github.com/JuliaBinaryWrappers/LibFramehopUnwind_jll.jl/releases/download/LibFramehopUnwind-v0.1.0+0/LibFramehopUnwind.v0.1.0.aarch64-linux-gnu.tar.gz"
[[LibFramehopUnwind]]
arch = "x86_64"
git-tree-sha1 = "77403f14106982789591c1370e8f372bc253d6fa"
os = "macos"

    [[LibFramehopUnwind.download]]
    sha256 = "c50f5cb29d1700367be70fdbd8bee4aca3e5495941f180a1acac4d5a38b4b99c"
    url = "https://github.com/JuliaBinaryWrappers/LibFramehopUnwind_jll.jl/releases/download/LibFramehopUnwind-v0.1.0+0/LibFramehopUnwind.v0.1.0.x86_64-apple-darwin.tar.gz"
[[LibFramehopUnwind]]
arch = "x86_64"
git-tree-sha1 = "f3db90bb65457093742b39a6f9efcabbe8b91ec5"
libc = "glibc"
os = "linux"

    [[LibFramehopUnwind.download]]
    sha256 = "699b2cbb055dd695fb5e3511934b44cb4f01b3be46f213c7d5c79478d50bc34e"
    url = "https://github.com/JuliaBinaryWrappers/LibFramehopUnwind_jll.jl/releases/download/LibFramehopUnwind-v0.1.0+0/LibFramehopUnwind.v0.1.0.x86_64-linux-gnu.tar.gz"
[[LibFramehopUnwind]]
arch = "x86_64"
git-tree-sha1 = "26fd80a007d2d185b166383b64fe3cfe1fe1b71f"
os = "freebsd"

    [[LibFramehopUnwind.download]]
    sha256 = "a5e73d1ee821cbcebfadabb1b76e7ba2349464e0ea8ef0612ac45a120c7f1019"
    url = "https://github.com/JuliaBinaryWrappers/LibFramehopUnwind_jll.jl/releases/download/LibFramehopUnwind-v0.1.0+0/LibFramehopUnwind.v0.1.0.x86_64-unknown-freebsd.tar.gz"
[[LibFramehopUnwind]]
arch = "x86_64"
git-tree-sha1 = "57cc6233117681200339c960fb47ef61b3daae69"
os = "windows"

    [[LibFramehopUnwind.download]]
    sha256 = "3e690c27dcfac92dca92ad868e1918210983d8e316a8fbab456953278535b53b"
    url = "https://github.com/JuliaBinaryWrappers/LibFramehopUnwind_jll.jl/releases/download/LibFramehopUnwind-v0.1.0+0/LibFramehopUnwind.v0.1.0.x86_64-w64-mingw32.tar.gz"
