# Autogenerated wrapper script for LibFramehopUnwind_jll for x86_64-apple-darwin
export framehopunwind_h, libframehopunwind, libframehopunwind_a

JLLWrappers.@generate_wrapper_header("LibFramehopUnwind")
JLLWrappers.@declare_file_product(framehopunwind_h)
JLLWrappers.@declare_library_product(libframehopunwind, "@rpath/libframehopunwind.dylib")
JLLWrappers.@declare_file_product(libframehopunwind_a)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        framehopunwind_h,
        "include/framehopunwind.h",
    )

    JLLWrappers.@init_library_product(
        libframehopunwind,
        "lib/libframehopunwind.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libframehopunwind_a,
        "lib/libframehopunwind.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
